import Nav from '../components/Nav';

// ── Style tokens ───────────────────────────────────────────────────────────

const LABEL: React.CSSProperties = {
  fontFamily:    'var(--font-mono)',
  fontSize:      '10px',
  letterSpacing: '2px',
  textTransform: 'uppercase',
  color:         'var(--ev-dim)',
};

const CARD: React.CSSProperties = {
  background:   'var(--ev-card)',
  border:       '1px solid var(--ev-border)',
  borderRadius: '2px',
};

const TERM: React.CSSProperties = {
  fontFamily:    'var(--font-mono)',
  fontSize:      '11px',
  letterSpacing: '2px',
  textTransform: 'uppercase',
  color:         'var(--ev-green)',
  fontWeight:    600,
};

const DEF: React.CSSProperties = {
  fontFamily: 'var(--font-mono)',
  fontSize:   '12px',
  lineHeight: 1.6,
  color:      'var(--ev-text)',
};

const STEP_TITLE: React.CSSProperties = {
  fontFamily:    'var(--font-syne)',
  fontWeight:    800,
  fontSize:      '14px',
  letterSpacing: '-0.3px',
  color:         'var(--ev-text)',
  marginBottom:  '6px',
};

const STEP_NUM: React.CSSProperties = {
  fontFamily:    'var(--font-mono)',
  fontSize:      '11px',
  fontWeight:    700,
  letterSpacing: '1px',
  color:         'var(--ev-green)',
  border:        '1px solid var(--ev-green)',
  borderRadius:  '50%',
  width:         '24px',
  height:        '24px',
  display:       'flex',
  alignItems:    'center',
  justifyContent: 'center',
  flexShrink:    0,
};

const SEC: React.CSSProperties = {
  fontFamily:    'var(--font-mono)',
  fontSize:      '9px',
  letterSpacing: '2px',
  textTransform: 'uppercase',
  color:         'rgba(255,255,255,0.4)',
  marginBottom:  '10px',
};

// ── How to find plays ──────────────────────────────────────────────────────

const STEPS: { title: string; def: string }[] = [
  {
    title: 'Start with ADJ%',
    def:   'Your primary signal. Look for 15%+ as a starting point. Color coding: green ≥18% (strong), gold 14–18% (moderate), white below 14% (low confidence). The higher the number, the more the model likes the play.',
  },
  {
    title: 'Check EDGE',
    def:   'Positive edge means the book is underpricing the probability relative to the model. Green edge = value — the bigger the green number, the more the model and the book disagree in your favor.',
  },
  {
    title: 'Confirm with Statcast',
    def:   'Open the expanded card and check BARREL% and HARD HIT% in the BATTER L15 section. An elite barrel rate (12%+) confirms the underlying power is real, not just a favorable matchup on paper.',
  },
  {
    title: 'Check the matchup',
    def:   "Look at PARK FACTOR and PITCHER FIP in the CONTEXT section. A park factor above 105 is hitter-friendly. A low pitcher FIP means they give up hard contact. Both together is the strongest combination.",
  },
  {
    title: 'Use AI PICKS',
    def:   'The AI PICKS tab does all of this automatically and surfaces the top plays ranked by confidence — a fast way to see what the model likes most without working through the table yourself.',
  },
];

// ── Views & sorting ────────────────────────────────────────────────────────

const VIEWS: { title: string; def: string }[] = [
  {
    title: 'BY EDGE (default)',
    def:   'All confirmed starters sorted by edge descending — players where the model has the biggest advantage over the book price appear first. Best for finding +EV spots quickly.',
  },
  {
    title: 'BY GAME',
    def:   'Players grouped by matchup, sorted by adj_prob within each game. Use this when you want to target a specific game or compare every starter in a single matchup at once.',
  },
  {
    title: 'AI PICKS',
    def:   'A curated shortlist generated by Claude. Filtered to players with a meaningful adj_prob and positive edge, then ranked by a composite score that weights probability, edge, barrel rate, and matchup. Typically 3–8 plays per slate.',
  },
];

// ── Book edge ──────────────────────────────────────────────────────────────

const EDGE_NOTES: { title: string; def: string }[] = [
  {
    title: 'Positive EDGE',
    def:   "The model's implied probability is higher than the book's. This is the definition of +EV — you're paying less for the bet than it's theoretically worth. Larger positive edge = more conviction.",
  },
  {
    title: 'Negative EDGE',
    def:   "The book is priced above the model's estimate. Not automatically a no-bet — if the ADJ% is high (18%+), the matchup is elite, and the odds are still reasonable (+250 or better), the play can still make sense as a high-confidence dart. Edge is one signal, not the only signal.",
  },
  {
    title: 'Edge = 0 (no line)',
    def:   "Shows — when the book has no line for that player. This often happens early in the day before props are posted, or for players at books with limited prop coverage. Check back closer to game time.",
  },
];

// ── Model probability ──────────────────────────────────────────────────────

const PROB_NOTES: { title: string; def: string }[] = [
  {
    title: 'What ADJ% means',
    def:   "The model's probability that this batter hits at least one home run today. It accounts for the batter's recent Statcast data (barrel%, exit velocity, fly ball rate), the opposing pitcher's allowed contact profile, park factor, weather, and batting order position.",
  },
  {
    title: 'Calibration (+2.78pp)',
    def:   "The raw model output is shifted up by 2.78 percentage points to correct a measured systematic underestimation bias. The shift is additive — it preserves relative rankings exactly. Every player's probability moves up uniformly.",
  },
  {
    title: 'Color thresholds',
    def:   'Green ≥18% — strong conviction play. Gold 14–18% — reasonable spot worth a second look. White below 14% — low probability; only worth it with unusually large positive edge.',
  },
  {
    title: 'FAIR odds',
    def:   'The American odds equivalent of ADJ%. If ADJ% is 20%, FAIR is +400. If a book is offering +450, that is above fair value — positive edge.',
  },
];

// ── AI Picks ───────────────────────────────────────────────────────────────

const AI_NOTES: { title: string; def: string }[] = [
  {
    title: 'Entry criteria',
    def:   'Only players with a confirmed lineup, a positive edge vs at least one book, and an adj_prob above a minimum threshold (typically ~12%) are eligible. Players without a book line are not included.',
  },
  {
    title: 'Composite score',
    def:   'Claude ranks eligible plays by a weighted score that considers: adj_prob (primary), edge vs best book (secondary), batter barrel% and hard hit% (confirmation), days since last HR, and matchup quality (park factor + pitcher FIP).',
  },
  {
    title: 'Odds cap',
    def:   'Plays at very long odds (above roughly +600) are penalized in the composite score. Long shots need an exceptionally high adj_prob and edge to make the list — a 5% probability at +1800 is not a pick regardless of edge.',
  },
  {
    title: 'Output',
    def:   'Typically 3–8 picks per slate with a brief rationale for each. The rationale references specific data points (barrel%, park, matchup) rather than generic commentary.',
  },
];

// ── Market odds ────────────────────────────────────────────────────────────

const BOOKS: { name: string; def: string }[] = [
  { name: 'Pinnacle',   def: 'The sharpest book in the world. Pinnacle accepts winning bettors and prices HR props with the tightest vig (~5%). If Pinnacle and the model disagree, pay attention — Pinnacle is rarely wrong. Use Pinnacle as the reference point for fair value.' },
  { name: 'FanDuel',    def: 'High liquidity, competitive HR prop coverage. One of the first to post lines each day. Occasionally softer on player props than on game lines.' },
  { name: 'DraftKings', def: 'Similar coverage to FanDuel. DK and FD are usually within a few cents of each other. When they diverge, line shop the difference.' },
  { name: 'BetRivers',  def: 'Smaller book with less sharp action. Can sometimes be slower to move lines, creating brief +EV windows that close quickly.' },
  { name: 'Novig',      def: 'A no-vig exchange. Lines are set by market participants, not the house, so there is no built-in juice. The price you see is close to true market value. Great for finding actual fair value without fighting vig.' },
  { name: 'BetMGM',     def: 'Competitive HR prop coverage. Occasionally differs from FD/DK, creating line shop opportunities.' },
];

// ── Glossary ───────────────────────────────────────────────────────────────

const GLOSSARY: { term: string; def: string }[] = [
  {
    term: 'ADJ%',
    def:  "Calibrated model probability the batter hits a HR today. Green ≥18%, gold 14–18%, white below.",
  },
  {
    term: 'FAIR',
    def:  "American odds equivalent of ADJ%. What the line should be at zero vig.",
  },
  {
    term: 'BOOK',
    def:  'Best available American odds across all tracked sportsbooks. Shows the book logo to the left of the price.',
  },
  {
    term: 'EDGE',
    def:  "adj_prob minus book's implied probability. Positive = model sees more value. Negative = book is priced above the model.",
  },
  {
    term: 'MY LINE',
    def:  'Enter any price you found. The tool recalculates your real edge at that specific odds.',
  },
  {
    term: 'BO',
    def:  'Batting order slot (1–9). Lower slots get more plate appearances per game.',
  },
  {
    term: 'H/A',
    def:  'Home (green) or Away. Home teams have a minor statistical advantage.',
  },
  {
    term: 'SZN HR',
    def:  'Season home run total to date.',
  },
  {
    term: 'DAYS SINCE HR',
    def:  'Days since the batter last hit a HR. Useful context but not a direct model input.',
  },
  {
    term: 'PARK FACTOR',
    def:  'HR-specific park factor. 100 = neutral. Green >105 (hitter-friendly), red <95 (pitcher-friendly).',
  },
  {
    term: 'O/U',
    def:  'Game over/under total. Higher totals tend to correlate with more HR-friendly environments.',
  },
  {
    term: 'HOT',
    def:  'Gold dot — batter hit a HR in their last 5 games.',
  },
  {
    term: 'BARREL%',
    def:  'Percentage of batted balls classified as barrels (exit velocity + launch angle combo most likely to produce XBH). League avg ~8.5%. 12%+ is elite.',
  },
  {
    term: 'HARD HIT%',
    def:  'Percentage of batted balls hit 95+ mph. League avg ~41%. 48%+ is elite.',
  },
  {
    term: 'FLY BALL%',
    def:  "Percentage of balls in play that are fly balls. Higher = more HR opportunities. League avg ~35%.",
  },
  {
    term: 'AVG EV',
    def:  'Average exit velocity on all batted balls (last 15 games). Directly correlates with power production.',
  },
  {
    term: 'xwOBA / xSLG',
    def:  'Expected weighted on-base average and expected slugging — based on quality of contact, not outcomes. Better predictors of future performance than actual wOBA/SLG.',
  },
  {
    term: 'PITCHER FIP',
    def:  "Fielding-independent pitching. Measures the pitcher's ERA based only on HR, K, BB, and HBP — strips out defense. Lower FIP = better pitcher. High FIP = exploitable.",
  },
  {
    term: 'PLATOON',
    def:  'HR totals split by opponent handedness (VS R / VS L). Helps identify platoon advantages — a left-handed batter vs a right-handed pitcher with a large VS R total is a meaningful edge.',
  },
];

// ── Page ───────────────────────────────────────────────────────────────────

export default function GuidePage() {
  return (
    <main style={{ minHeight: '100vh', background: 'var(--ev-bg)', padding: '32px 20px 60px' }}>
      <div style={{ maxWidth: '1380px', margin: '0 auto' }}>

        {/* Header */}
        <header style={{ marginBottom: '28px' }}>
          <div style={{ ...LABEL, color: 'var(--ev-green)', letterSpacing: '3px', marginBottom: '8px' }}>
            THE +EV CAVE
          </div>
          <h1 style={{
            fontFamily: 'var(--font-syne)', fontWeight: 800, fontSize: '26px',
            margin: 0, letterSpacing: '-0.5px', color: 'var(--ev-text)',
          }}>
            GUIDE
          </h1>
        </header>

        <Nav active="guide" />

        {/* How to find plays */}
        <div style={{ ...CARD, padding: '20px 24px', marginBottom: '16px' }}>
          <div style={{ ...LABEL, marginBottom: '4px' }}>HOW TO FIND PLAYS</div>
          <p style={{ ...DEF, margin: '0 0 18px', color: 'var(--ev-muted)' }}>
            A simple five-step process for turning the table into a short list of plays worth a look.
          </p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
            {STEPS.map((step, i) => (
              <div key={step.title} style={{ display: 'flex', gap: '14px', alignItems: 'flex-start' }}>
                <div style={STEP_NUM}>{i + 1}</div>
                <div>
                  <div style={STEP_TITLE}>{step.title}</div>
                  <div style={{ ...DEF, color: 'var(--ev-muted)' }}>{step.def}</div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Views & Sorting */}
        <div style={{ ...CARD, padding: '20px 24px', marginBottom: '16px' }}>
          <div style={{ ...LABEL, marginBottom: '14px' }}>VIEWS & SORTING</div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
            {VIEWS.map(({ title, def }) => (
              <div key={title}>
                <div style={{ ...SEC, marginBottom: '4px' }}>{title}</div>
                <div style={{ ...DEF, color: 'var(--ev-muted)' }}>{def}</div>
              </div>
            ))}
          </div>
        </div>

        {/* How to use MY LINE */}
        <div style={{ ...CARD, padding: '20px 24px', marginBottom: '16px' }}>
          <div style={{ ...LABEL, marginBottom: '10px' }}>HOW TO USE MY LINE</div>
          <p style={{ ...DEF, margin: 0, color: 'var(--ev-muted)' }}>
            The FAIR column shows what a player&apos;s home run odds should be based on the model&apos;s
            probability. If you can get a better price than FAIR on an exchange like Novig, you&apos;re
            buying in at a discount. Enter that price into MY LINE to see your real edge at the
            odds you can actually get — a green MY LINE edge means the price you found beats the
            model&apos;s fair value, which is exactly the kind of spot worth taking.
          </p>
        </div>

        {/* Market Odds */}
        <div style={{ ...CARD, padding: '20px 24px', marginBottom: '16px' }}>
          <div style={{ ...LABEL, marginBottom: '6px' }}>MARKET ODDS — THE 6 BOOKS</div>
          <p style={{ ...DEF, margin: '0 0 16px', color: 'var(--ev-muted)' }}>
            When you expand a player row the MARKET ODDS section shows the anytime HR price at each tracked
            book. A dash (—) means that book has no line posted yet — check back closer to first pitch.
          </p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
            {BOOKS.map(({ name, def }) => (
              <div key={name}>
                <div style={{ ...TERM, marginBottom: '3px' }}>{name}</div>
                <div style={{ ...DEF, color: 'var(--ev-muted)' }}>{def}</div>
              </div>
            ))}
          </div>
        </div>

        {/* DFS Lines */}
        <div style={{ ...CARD, padding: '20px 24px', marginBottom: '16px' }}>
          <div style={{ ...LABEL, marginBottom: '10px' }}>DFS LINES</div>
          <p style={{ ...DEF, margin: '0 0 14px', color: 'var(--ev-muted)' }}>
            The DFS LINES section shows HR prop lines from PrizePicks and Underdog Fantasy.
            DFS lines work differently from sportsbooks — you are picking Over or Under a set number
            rather than betting against a spread.
          </p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
            <div>
              <div style={{ ...SEC, marginBottom: '4px' }}>PRIZEPICKS — standard juice -119</div>
              <div style={{ ...DEF, color: 'var(--ev-muted)' }}>
                Break-even at 54.4% win rate. PrizePicks offers single-player entries (Flex) with
                no parlay requirement. The -119 price on most HR props means you need to be right
                54.4% of the time to break even. Use ADJ% to filter entries — look for plays where
                the model gives 18%+ as a starting point.
              </div>
            </div>
            <div>
              <div style={{ ...SEC, marginBottom: '4px' }}>UNDERDOG FANTASY — standard -115 (ALT lines vary)</div>
              <div style={{ ...DEF, color: 'var(--ev-muted)' }}>
                Break-even at 53.5% on standard lines. Underdog also offers ALT lines at adjusted
                prices — e.g. a player with a standard 0.5 HR line may have an ALT line at 1.5 HRs
                at a much higher price, or 0.5 HRs with a boosted payout. ALT lines are shown when
                available and noted with the line value.
              </div>
            </div>
          </div>
          <p style={{ ...DEF, margin: '12px 0 0', color: 'rgba(255,255,255,0.25)', fontSize: '11px' }}>
            Note: DFS lines populate from the pipeline. If lines show — the data has not yet been
            pulled for today&apos;s slate.
          </p>
        </div>

        {/* Model probability */}
        <div style={{ ...CARD, padding: '20px 24px', marginBottom: '16px' }}>
          <div style={{ ...LABEL, marginBottom: '14px' }}>MODEL PROBABILITY</div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
            {PROB_NOTES.map(({ title, def }) => (
              <div key={title}>
                <div style={{ ...SEC, marginBottom: '4px' }}>{title}</div>
                <div style={{ ...DEF, color: 'var(--ev-muted)' }}>{def}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Book edge */}
        <div style={{ ...CARD, padding: '20px 24px', marginBottom: '16px' }}>
          <div style={{ ...LABEL, marginBottom: '14px' }}>BOOK EDGE</div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
            {EDGE_NOTES.map(({ title, def }) => (
              <div key={title}>
                <div style={{ ...SEC, marginBottom: '4px' }}>{title}</div>
                <div style={{ ...DEF, color: 'var(--ev-muted)' }}>{def}</div>
              </div>
            ))}
          </div>
        </div>

        {/* AI Picks */}
        <div style={{ ...CARD, padding: '20px 24px', marginBottom: '16px' }}>
          <div style={{ ...LABEL, marginBottom: '6px' }}>AI PICKS</div>
          <p style={{ ...DEF, margin: '0 0 14px', color: 'var(--ev-muted)' }}>
            The AI PICKS view runs Claude against the full slate and produces a curated shortlist
            with written rationale. It is not a simple sort — it is a multi-factor filter that
            weights the same signals an experienced bettor would consider.
          </p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
            {AI_NOTES.map(({ title, def }) => (
              <div key={title}>
                <div style={{ ...SEC, marginBottom: '4px' }}>{title}</div>
                <div style={{ ...DEF, color: 'var(--ev-muted)' }}>{def}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Alert badge — K tool */}
        <div style={{ ...CARD, padding: '20px 24px', marginBottom: '16px' }}>
          <div style={{ ...LABEL, marginBottom: '10px' }}>
            ! ALERT BADGE{' '}
            <span style={{ color: 'rgba(255,255,255,0.3)', letterSpacing: '1px' }}>
              — STRIKEOUT TOOL ONLY
            </span>
          </div>
          <p style={{ ...DEF, margin: '0 0 12px', color: 'var(--ev-muted)' }}>
            On the strikeout (K) tool, a yellow{' '}
            <span style={{ color: 'var(--ev-gold)', fontWeight: 600 }}>!</span>{' '}
            badge appears next to a pitcher when the model&apos;s projected strikeout total
            (ADJ K) differs from the book&apos;s posted line by more than 1 full strikeout.
          </p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
            <div>
              <div style={{ ...SEC, marginBottom: '4px' }}>ADJ K &gt; BOOK LINE + 1</div>
              <div style={{ ...DEF, color: 'var(--ev-muted)' }}>
                The model projects significantly more strikeouts than the book is pricing.
                This is an Over alert — the model sees meaningful value on the Over.
              </div>
            </div>
            <div>
              <div style={{ ...SEC, marginBottom: '4px' }}>ADJ K &lt; BOOK LINE - 1</div>
              <div style={{ ...DEF, color: 'var(--ev-muted)' }}>
                The model projects significantly fewer strikeouts than the book is pricing.
                This is an Under alert — the model sees value on the Under side.
              </div>
            </div>
          </div>
        </div>

        {/* Glossary */}
        <div style={{ ...CARD, padding: '20px 24px' }}>
          <div style={{ ...LABEL, marginBottom: '16px' }}>COLUMN GLOSSARY</div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: '20px 32px' }}>
            {GLOSSARY.map(({ term, def }) => (
              <div key={term}>
                <div style={{ ...TERM, marginBottom: '4px' }}>{term}</div>
                <div style={DEF}>{def}</div>
              </div>
            ))}
          </div>
        </div>

      </div>
    </main>
  );
}
